/*******************************************************************************
© Copyright 2003. The U.S. Government, as Represented by the Administrator of
the National Aeronautics and Space Administration (NASA). All rights reserved.
Includes content licensed from the U.S. Government, National Aeronautics and
Space Administration under United States Copyright Registration Numbers
V3503D364 and V3482D344.
© 2008-2015 NPSS® Consortium, www.NPSSConsortium.org/AllRightsReserved
*******************************************************************************/

/*******************************************************************************
NPSS® software and related documentation is export controlled with an Export
Control Classification Number(ECCN) of 9D991, controlled for Anti-Terrorism
reasons, under U.S. Export Administration Regulations 15 CFR 730-774. It may
not be transferred to a country checked under anti-terrorism on the Commerce
Country Chart structure or to foreign nationals of those countries in the U.S.
or abroad without first obtaining a license from the Bureau of Industry and
Security, United States Department of Commerce. Violations are punishable by
fine, imprisonment, or both.
*******************************************************************************/

//include viewers
#include "npssel.view"
#include "npssel_runtime.view"

// include consortium port desired changes
#include "consort_fix.fnc"

MODELNAME = "3 Phase Example";

// select model
#include "AC_3phase_example.mdl"

autoSolverSetup();

//---------------------------------------------------------
// just like a rocket engine, volumes last
//---------------------------------------------------------
solver.debugLevel = "ITERATION_DETAILS";
solver.diagnosticFile = "output/Solver.bad";

solver.maxIterations = 5000;
solver.maxJacobians = 1000;

setOption("ElectricPowerType", "AC3");

solver.debugLevel = "ITERATION_DETAILS";
solver.diagnosticFile = "output/solver.bad";
 
run();

page.display();  // output data to out file
page_runtime.display(); // output data to cmd window

cout<<" \n ===============================================" << endl;
cout<<" Complex " << endl;

cout<< " Current A1 (in) : " << A1.EP_I.I.getReal() << "  + j" << A1.EP_I.I.getImag() << "\n" << endl;

cout<< " Voltage Source  : " << Source.EP_Oa.V.getReal() << "  + j" << Source.EP_Oa.V.getImag() << endl;
cout<< " Voltage A1 (out): " << A1.EP_O.V.getReal() << "  + j" << A1.EP_O.V.getImag() << endl;
cout<< " Voltage line drop (out): " << Source.EP_Oa.VLN.getReal()-A1.EP_O.VLN.getReal() << "  + j" << Source.EP_Oa.VLN.getImag()-A1.EP_O.VLN.getImag() << endl;
cout<< " Voltage A1 LN (out): " << A1.EP_O.VLN.getReal() << "  + j" << A1.EP_O.VLN.getImag() << "\n" << endl;
cout<< " Voltage A2 (out): " << A2.EP_O.V.getReal() << "  + j" << A2.EP_O.V.getImag() << "\n" << endl;

cout<< " Power Source  : " << Source.EP_Oa.S.getReal() << "  + j" << Source.EP_Oa.S.getImag() << endl;
cout<< " Power A1 (out): " << A1.EP_O.S.getReal() << "  + j" << A1.EP_O.S.getImag() << endl;
cout<< " Power A2 (out): " << A2.EP_O.S.getReal() << "  + j" << A2.EP_O.S.getImag() << "\n" << endl;
cout<< " Load PF (out): " << cos(arg_c(A1.EP_O.S)) << "\n" << endl;
cout<< " Load impedance (out): " << A2.Z.getReal() << "  + j" << A2.Z.getImag()/(2*3.14*60) << "\n" << endl;


cout<<" \n ===============================================" << endl;
cout<<" Phasors " << endl;
cout<< " Current A1 (in) : " << abs_c(A1.EP_I.I) << " /_ " << arg_c(A1.EP_I.I)*180/PI << "\n" << endl;

cout<< " Voltage Source  : " << abs_c(Source.EP_Oa.V) << " /_  " << arg_c(Source.EP_Oa.V)*180/PI << endl;
cout<< " Voltage A1 (out): " << abs_c(A1.EP_O.V) << " /_  " << arg_c(A1.EP_O.V)*180/PI << endl;
cout<< " Voltage A2 (out): " << abs_c(A2.EP_O.V) << " /_  " << arg_c(A2.EP_O.V)*180/PI << "\n" << endl;

cout<< " Power Source  : " << abs_c(Source.EP_Oa.S) << " /_  " << arg_c(Source.EP_Oa.S)*180/PI << endl;
cout<< " Power A1 (out): " << abs_c(A1.EP_O.S) << " /_  " << arg_c(A1.EP_O.S)*180/PI << endl;
cout<< " Power A2 (out): " << abs_c(A2.EP_O.S) << " /_  " << arg_c(A2.EP_O.S)*180/PI << "\n" << endl;
cout<<" =============================================== \n" << endl;

cout << endl << "Solver Sequence:" << endl << solverSequence << endl;
cout << "Dependents:" << endl << solver.dependentNames << endl;
cout << "Independents:" << endl << solver.independentNames << endl;